import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LoadingProvider } from '@/context/LoadingContext';
import LoadingOverlay from '@/components/LoadingOverlay';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AutoMeet",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/meta.png', type: 'image/png' },  // Adjust filename to match your image
      { url: '/favicon.ico' }
    ],
    apple: [
      { url: '/meta.png', type: 'image/png' }  
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LoadingProvider>
          <LoadingOverlay />
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}
